[package]
name = "beg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
# [[bin]]
# name = "rust-learning"
# path = "main.rs"
